# Generated by Django 4.2.7 on 2023-11-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda_electronica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='imagenes_productos/default.jpg', upload_to='imagenes_productos/'),
        ),
    ]
