# Generated by Django 4.2.7 on 2023-11-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda_electronica', '0004_cliente_is_active_alter_cliente_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
