# Generated by Django 4.2.7 on 2023-11-21 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda_electronica', '0006_perfil_alter_pedido_cliente_delete_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nombre',
        ),
    ]
