# Generated by Django 4.2.7 on 2023-11-22 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_tienda_electronica', '0007_remove_perfil_apellido_remove_perfil_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tarjeta', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito')], default='credito', max_length=10)),
                ('nombre_titular', models.CharField(max_length=100)),
                ('ultimos_digitos', models.CharField(max_length=4)),
                ('fecha_expiracion', models.DateField()),
                ('metodo_pago_token', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
            },
        ),
    ]
