# Generated by Django 4.2.7 on 2023-11-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda_electronica', '0009_rename_metodo_pago_token_metodopago_numero_tarjeta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metodopago',
            old_name='ultimos_digitos',
            new_name='cvv',
        ),
    ]
