# Generated by Django 4.2.7 on 2023-11-22 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda_electronica', '0010_rename_ultimos_digitos_metodopago_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
